### ISSUE TITLE
Compatibility with Lab3

### ISSUE THREAD

**Issue by diocas** [rucio/jupyterlab-extension#1]
Hi guys, 

Lab 3 was released early this year and brings some changes on how extensions are built and deployed. The current extension is thus incompatible. How can we proceed to update this extension?

The Jupyter team has provided a guide and even some tools to ease the transition: https://jupyterlab.readthedocs.io/en/latest/extension/extension_migration.html

Diogo

**Comment by didithilmy** [comment]
I don't think the migration would be difficult, I could make a PR to update the extension. But, updating means that we lose compatibility to Lab2. Is that okay for now? Or maybe, we could create a different branch to support Lab3?

**Comment by mlassnig** [comment]
Hi, the proper approach would be to git tag the current master as "latest stable for lab2" and move it to a "lab2" branch, and continue development for lab3 on the master.

**Comment by bari12** [comment]
I would just tag the current head as `lab2-latest` and then continue on top of master. If we ever need to update the lab2 plugin code, we can make a branch.
The `lab2-latest` just needs to be mentioned in the readme.
Thanks a lot @didithilmy for still looking into this :-)

**Comment by diocas** [comment]
Thanks @didithilmy ! Good to see a GSoC project that becomes a long lasting collaboration.
 Ping us if you need any help.

**Comment by didithilmy** [comment]
No problem, glad to help! I won't let three months of hard work goes to waste :)

I have pushed tag `lab2-latest` and created `lab2` branch.
Also, I've made PR #2, please check if there's any problem with that. I have run it in development mode on my laptop, but I didn't connect it to a Rucio instance. It seems to be working fine.
