### ISSUE TITLE
Failing test build

### ISSUE THREAD

**Issue by goseind** [rucio/jupyterlab-extension#22]
Because of outdated dependencies, the test build of the extension seems to fail.

For example https://github.com/rucio/jupyterlab-extension/actions/runs/6225180068
![grafik](https://github.com/rucio/jupyterlab-extension/assets/87760323/9de6b722-e16f-4d26-86c5-f153aaf2e6d4)

Once fixed the bdage for both workflows in the readme should be updated, as they are not displayed correctly.

This guide might be needed to migrate to JL v4: https://jupyterlab.readthedocs.io/en/latest/extension/extension_migration.html

**Comment by ftorradeflot** [comment]
Closing this issue since the test workflow was fixed a while ago and I fixed the badges in the README. Upgrading Jupyterlab to v4 is an independent task (#27 )
