### ISSUE TITLE
Question: Variable failed to attach

### ISSUE THREAD

**Issue by artfisica** [rucio/jupyterlab-extension#3]
Dear All,

Thanks for such a nice and useful job done with this tool!

I have been using the extension since a few days ago, and I have a problem where even when I find and successfully download a dataset, I can't attach a variable in a Python3 kernel notebook.

I am not sure if this is the right forum, but can I ask where to explore the reason for this failure? Or any other advice you can give me

Your help is very much appreciated, 

Cheers,
Arturo

![Screenshot 2021-03-01 at 21 50 21](https://user-images.githubusercontent.com/8846121/109557339-425f5280-7ad8-11eb-9a20-1a7ed6e08651.png)

**Comment by didithilmy** [comment]
Hi there, have you tried to attach other DIDs? If yes, did it work?

**Comment by artfisica** [comment]
Hi!

Thanks for the reply. No, I did not try another dataset; I will do so and let you know.
What I did was to try in a couple of different notebooks (same kernel, of course)

**Comment by didithilmy** [comment]
So there are a couple of scenarios of why the attachment could fail:
1. The kernel extension wasn't properly installed, or
2. The server extension somehow failed to resolve the paths.
Given that you have successfully downloaded the files, I suppose number (1) is more likely. You could see if the Kernel extension has been loaded by running seeing if the function `resolve_dids` exists.

It should show something like this:
<img width="582" alt="Screen Shot 2021-03-02 at 14 27 36" src="https://user-images.githubusercontent.com/4845621/109613241-76338a00-7b63-11eb-9657-cd5a1155a2d9.png">

For instructions on how to load the Kernel extension, take a look at this link: https://github.com/rucio/jupyterlab-extension/blob/master/CONFIGURATION.md#ipython-kernel

Hope it helps!

**Comment by artfisica** [comment]
Thank you again, @didithilmy :)

I tried with another dataset, but yes, the result is the same.

Also, following your instructions, I see that yes, it looks like I don't have such a kernel extension.
I see also the instructions, but yes, I don't get the same result as you when doing ```resolve_dids```

Sorry for the naive question, but could it be that I need to install something after the Jupyterlab and the extension?

I mean, after the JupyterLab installation, I have (in the Docker creation):

```
    && python3.6 -m pip install rucio-jupyterlab \
    && jupyter nbextension enable --py widgetsnbextension \
    && jupyter labextension install @jupyter-widgets/jupyterlab-manager@2.0 --debug --minimize=False --dev-build=False \
    && jupyter lab build --minimize=False --dev-build=False
```

Another screenshot attached :)
![Screenshot 2021-03-02 at 09 58 04](https://user-images.githubusercontent.com/8846121/109624537-9dc42b80-7b3e-11eb-9d96-332325b8e747.png)

**Comment by didithilmy** [comment]
So after you run the line that loads the kernel ext, you should re-inject the variables. You can do that by clicking on the “Failed to Attach” button on the top right.

**Comment by artfisica** [comment]
Oh, thanks!

No way you can believe me that I did that before, and it did not work for me :)


I understand now that restart the kernel also means executing and re-injecting the variables (maybe an obvious comment, but this post will help me in the future, I am sure).

Ok, now it works (see the screenshot, please), so a question I should ask is:
* If we distribute this tool to users, do we need to tell them about this first cell content? 
* Or better say, is it possible to "repair" my setup so that this is extra ```%load_ext``` unnecessary in every notebook?
   * question connected with the fact that the last cell yet did not output the same as you have.
   
![Screenshot 2021-03-02 at 11 06 36](https://user-images.githubusercontent.com/8846121/109632509-6443ee00-7b47-11eb-8725-d88e29df4a68.png)
?

**Comment by didithilmy** [comment]
I would suggest that you configure your JupyterLab installation so that you don’t include the first line. You can do that by creating an IPython config file (see the previous link).

As for the last cell, I believe that you have a typo, it should be `resolve_dids`, not `resolve_dsdi`. If the attachment works, then you’re all set :)

**Comment by artfisica** [comment]
Hi @didithilmy,

Thank you very much! Yes, it works, I added in my docker creation, and now the file is in the setup by default.

Great support and excuses for the delay to reply back.

I may have another question, but I will leave it to another issue to keep it in a single subject.

Thanks and cheers,
Arturo

**Comment by didithilmy** [comment]
Great! Happy to help. I'm closing this issue, then.
